### PR TITLE
Issue 199 details elements

### PR DESCRIPTION
**Pull request by martindholmes**
Implementation of issue #199. Tested in DVPP, which has lots of complexity and details elements.

### CODE REVIEW

**Comment by joeytakeda** [comment]
Should we put the detail opening logic into its own function? That would be much easier to override or remove if, say, someone wanted to do something else with the ancestor of the set of changed controls (especially if they weren’t details).

**Comment by martindholmes** [comment]
Hmm. I think that's a different feature request, to be honest, but I don't think there are any other elements that work like details in terms of hiding stuff on the page (without CSS).

**Comment by joeytakeda** [comment]
Really it's just an infrastructural concern—I see no harm in moving the bit from 590-599 to its own small function, but do see a number of benefits (it becomes overridable, easier to trace and debug, better documentation because of JSDocs).

**Comment by martindholmes** [comment]
Point taken, and I'll go ahead and do that.

**Comment by martindholmes** [comment]
Done. Tested again in DVPP, and seems to be working well.

**Comment by joeytakeda** [comment]
Thanks! Looks good to me and works well locally — will merge this in now.

**Pull request merged**
