### PR TITLE
New initial section on requirements, as suggested by @ebeshero.

### PR DESCRIPTION
**Pull request by martindholmes**
I've just followed @ebeshero's suggestion in issue #224 to add an initial section setting out requirements.

### CODE REVIEW

**Comment by joeytakeda** [comment]
Looks good to me--thanks! Just wanted to confirm that we wanted to merge this into dev, right? (If that's the case, then just feel free to merge :-)

**Comment by ebeshero** [comment]
@martindholmes @joeytakeda looks good to me as well! It didn't need to be a lot, but it's good to ensure we know going in what Windows will require. Indeed I'm pretty sure there's a reasonable ant solution to the Windows filepath trouble, so I hope we'll revisit that... I never did test `pathconvert` but I'd like to try it. Meanwhile, my students are implementing staticSearch on a project website on our college history--an archive of revised/polished up semester projects from earlier classes they took in the past couple of years. It should be ready to share as they wrap up work in a couple of weeks!

**Comment by martindholmes** [comment]
Since Windows is now supported, this must be revised before merging.

**Comment by martindholmes** [comment]
If we add ant-contrib (issue #260) to the repo, then we'll have to remove that bit as well.

**Review by martindholmes — COMMENTED** [review]
I'm going to kill this and just edit directly in dev, since we're now supporting Windows.

**Pull request closed without merging**
